cookie:
  expiry_days: 30
  key: bfc9f01de996b4085bc4aa70120b1c5d33be45eacc0a5f2f5b1841a0e6702f53d0c91cccf17981ddac8c14b5f413d3ab5bdafa2360ca6047a3da5db12167d66c
  name: bz323VBxrY
credentials:
  usernames:
    admins:
      email: 316262048@pcpuma.acatlan.unam.mx
      name: Sergio Lopez Martinez
      password: $2b$12$9b0Wt6y4xbKKnshMPA1VheBsIaqb1vwjznAw.MyNuRG5IX./2QV2i
    alumno1:
      email: rbriggs@gmail.com
      name: Juan Perez
      password: def
preauthorized:
  emails:
  - melsby@gmail.com
